name: Daily Weather Report

on:
  schedule:
    # 每天早上 8 點執行 (UTC+8)
    - cron: '0 0 * * *'  # UTC 時間 00:00，對應台灣時間 08:00
  workflow_dispatch:  # 允許手動觸發

jobs:
  send-weather-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 確保您有 requirements.txt 文件
        
    - name: Run weather report script
      env:
        # 如果您的程式需要環境變數，請在 GitHub Secrets 中設置
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        # 其他需要的環境變數...
      run: python main.py 